import type { Metadata } from "next";
import '@/styles/reset.css';

export const metadata: Metadata = {
	title: "Yomune",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body>{children}</body>
		</html>
	);
}
